Integreat/integreat-react-native-app

package.json, src/modules/common/components/Page.js, src/modules/common/renderHtml.js, yarn.lock
Fixes the height of the webview (also upgrades the webview version).
=> NATIVE-32: Fix Webview height

src/modules/endpoint/sagas/loadCategories.js, src/modules/endpoint/sagas/loadCityContent.js, src/modules/endpoint/sagas/loadEvents.js
A major performance improvement...
=> NATIVE-254: Scan urls only if necessary

src/modules/endpoint/DatabaseConnector.js, src/modules/endpoint/DatabaseContext.js, src/modules/endpoint/DefaultDataContainer.js
I thought the app did not start in the dev branch. That was because there were some local files (cities.json) still present which held the wrong data (as of the city-mapping-task). After deleting the app files  (several times) it finally did work, but I already made some changes, that streamlines the DatabaseConnector, so I thought I'd still opened a PR for it.
=> NATIVE-339: Add cache for cities

src/modules/app/StoreActionType.js, src/modules/app/components/Navigator.js, src/modules/app/containers/NavigatorContainer.js, src/modules/endpoint/sagas/loadCities.js, src/modules/endpoint/sagas/loadCityContent.js, src/modules/endpoint/sagas/watchFetchCities.js, src/routes/landing/containers/LandingContainer.js
I accidentally started (and finished) working on this, so I thought I'd open a PR although this issue has not been in this sprint.
=> NATIVE-325: Add pull to refresh to landing

.gitmodules
In order to apply these changes you have to do: git submodule resync
=> NATIVE-365: Make submodule url relative

package.json, src/modules/categories/components/Categories.js, src/routes/events/components/Events.js, src/routes/extras/components/Extras.js, src/routes/feedback/FeedbackVariant.js, src/routes/feedback/components/FeedbackModal.js, yarn.lock
Please review https://github.com/Integreat/integreat-api-client/pull/22 first
=> NATIVE-400: Add category to feedback

src/modules/categories/components/CategoryListItem.js, src/modules/theme/constants/dimensions.js, src/routes/search/components/SearchModal.js
I have no idea why, but it works. (I gave one of the `View`s a `minHeight`)
=> NATIVE-430: Search result not clickable when only one result

jest.config.js, package.json, src/modules/categories/components/CategoryListItem.js, src/modules/common/normalize.js, src/modules/common/normalizeSearchString.js, src/routes/landing/components/CityEntry.js, src/routes/landing/components/CitySelector.js, src/routes/landing/components/FilterableCitySelector.js, src/routes/landing/containers/LandingContainer.js, src/routes/search/components/SearchModal.js, yarn.lock
NATIVE-485: Use normalized city name and aliases for searching landing page,
NATIVE-452: Search for aliases
=> NATIVE-485 and NATIVE-452: Adjust search

src/routes/landing/components/Landing.js
=> NATIVE-421: Make whole background white on LandingPage

src/routes/feedback/components/FeedbackModal.js
comment is now required for negative feedback.
Also added an asterisk with increased font size and red color to mark the field as required.
Note: The asterisk is hardly visible in the normal font size. If you increase the font size, the distance between Combobox and text will also increase. Any tips for this style issue? @Schedulaar
=> NATIVE-508: Make text required for negative feedback

src/modules/common/components/SiteHelpfulBox.js
=> NATIVE-535: Use white background for feedback icons

src/modules/common/renderHtml.js
=> WEBAPP-507: Make pre scroll

locales/locales.json, src/routes/search/components/SearchHeader.js, src/routes/search/components/SearchModal.js, src/routes/search/components/ThemedSearchBar.js
=> NATIVE-385: Search placeholder

package.json, src/modules/app/__tests__/CategoriesRouteStateView.spec.js, src/modules/categories/components/CategoryList.js, src/modules/categories/components/__tests__/Categories.spec.js, src/modules/endpoint/DatabaseConnector.js, src/modules/endpoint/ResourceURLFinder.js, src/modules/endpoint/__tests__/DatabaseConnector.spec.js, src/modules/endpoint/reducers/__tests__/citiesReducer.spec.js, src/modules/endpoint/reducers/__tests__/cityContentReducer.spec.js, src/modules/endpoint/reducers/__tests__/morphContentLanguage.spec.js, src/modules/endpoint/reducers/__tests__/pushCategory.spec.js, src/modules/endpoint/reducers/__tests__/pushEvent.spec.js, src/routes/categories/containers/__tests__/CategoriesContainer.spec.js, src/routes/dashboard/components/Dashboard.js, src/routes/dashboard/containers/__tests__/DashboardContainer.spec.js, src/routes/disclaimer/DisclaimerContainer.js, src/routes/events/components/Events.js, src/routes/events/components/__tests__/Events.spec.js, src/routes/landing/components/CityEntry.js, src/routes/landing/getNearbyPlaces.js, src/routes/search/components/SearchModal.js, src/routes/sprungbrett/containers/SprungbrettExtraContainer.js, src/routes/wohnen/containers/WohnenExtraContainer.js, src/testing/builder/CityModelBuilder.js, src/testing/builder/EventModelBuilder.js, yarn.lock
=> WEBAPP-518: Fix api client flow types

src/modules/categories/components/CategoryListItem.js
=> NATIVE-555: Make category search less obstrusive

src/routes/landing/components/CityEntry.js, src/routes/landing/components/CityGroup.js
I need to fix 2 lines which are too long at the moment. (lint max-len)
=> NATIVE-554: Make alias search less obstrusive

src/modules/endpoint/sagas/watchContentLanguageSwitch.js
=> NATIVE-22: unsubscribe before setting new langauge in storage

fastlane/Fastfile
=> NATIVE-568: Add info about IDFA

ios/Integreat.xcodeproj/project.pbxproj, ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat-e2e.xcscheme, ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat-test-cms.xcscheme, ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat.xcscheme, ios/Integreat.xcodeproj/xcshareddata/xcschemes/malte.xcscheme, ios/Integreat/Info.plist
=> NATIVE-584: Remove frameworks and disable analytics

tools/next-version, version.json
=> NATIVE-594: FIx version code

.circleci/config.yml, .circleci/src/jobs/deliver_android.yml
=> NATIVE-591: Fix uploading to browserstack

src/routes/feedback/components/FeedbackModal.js, src/routes/intro/CustomizableIntroSettings.js, src/routes/intro/IntroContainer.js, src/routes/intro/IntroSettings.js, src/routes/search/components/NothingFoundFeedbackBox.js, src/routes/settings/createSettingsSections.js
=> NATIVE-558: Add appName to translate functions

ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat-e2e.xcscheme, ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat-test-cms.xcscheme, ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat.xcscheme, ios/Integreat.xcodeproj/xcshareddata/xcschemes/malte.xcscheme, ios/fastlane/README.md
=> NATIVE-592: App crashes on ios

.circleci/config.yml, .circleci/src/@workflows.yml, .circleci/trigger-pipeline, docs/cicd.md
=> NATIVE-609: Migrate to main

.circleci/config.yml, .circleci/src/jobs/prepare_delivery.yml, tools/bump-version, tools/constants.js, tools/parse-release-notes
=> NATIVE-616: Fix release notes

.circleci/config.yml, .circleci/src/commands/notify_failed.yml, .circleci/src/jobs/build_android.yml, .circleci/src/jobs/build_ios.yml, .circleci/src/jobs/deliver_android.yml, .circleci/src/jobs/deliver_ios.yml, .circleci/src/jobs/e2e.yml, .circleci/src/jobs/prepare_build.yml, .circleci/src/jobs/prepare_delivery.yml
=> NATIVE-546: Notify about failed buids on main

build-configs/configs/BuildConfigType.js, build-configs/configs/integreat/index.js, build-configs/configs/malte/index.js, src/modules/layout/components/Header.js
=> NATIVE-606: Make share path configurable

build-configs/configs/BuildConfigType.js, build-configs/configs/integreat/index.js, build-configs/configs/malte/index.js, src/modules/app/__tests__/createNavigateToIntegreatUrl.spec.js, src/modules/app/createNavigateToInternalLink.js, src/modules/categories/components/Categories.js, src/modules/categories/components/__tests__/Categories.spec.js, src/modules/common/components/Page.js, src/routes/categories/containers/CategoriesContainer.js, src/routes/categories/containers/__tests__/CategoriesContainer.spec.js, src/routes/dashboard/components/Dashboard.js, src/routes/dashboard/containers/DashboardContainer.js, src/routes/dashboard/containers/__tests__/DashboardContainer.spec.js, src/routes/events/components/Events.js, src/routes/events/components/__tests__/Events.spec.js, src/routes/events/containers/EventsContainer.js, src/routes/pois/components/Pois.js, src/routes/pois/containers/PoisContainer.js
=> NATIVE-605: Implement internal linking

release-notes/unreleased/NATIVE-384-FixCityNameLinking.yml, src/modules/layout/components/Header.js, src/modules/layout/containers/HeaderContainer.js
=> NATIVE-384: Show correct city when linking internally

.circleci/config.yml, .circleci/src/@workflows.yml, tools/create-jira-release
=> NATIVE-633: Fix parameters

android/app/buildConfigs.gradle
=> NATIVE-608: Fixed Windows' Yarn-Path error by using OS conditions

release-notes/unreleased/NATIVE-601-FixSettings.yml, release-notes/unreleased/NATIVE-622-FixSentry.yml, src/modules/endpoint/sagas/loadCityContent.js, src/modules/endpoint/sagas/watchContentLanguageSwitch.js, src/modules/i18n/watchClearCity.js, src/modules/notifications/NotificationsManager.js, src/modules/notifications/__mocks__/NotificationsManager.js, src/routes/settings/components/Settings.js, src/routes/settings/container/SettingsContainer.js, src/routes/settings/createSettingsSections.js
=> NATIVE-601: Fix push notification settings

.circleci/config.yml, .circleci/src/jobs/prepare_delivery.yml
=> NATIVE-641: Fix development release notes

build-configs/integreat/index.js, build-configs/malte/index.js, release-notes/unreleased/NATIVE-634-EnableNewsStream.yml
=> NATIVE-634: Enable news stream

docs/technical-documentation.md, docs/whitelabelling.md
=> NATIVE-642: Whitelabelling docu
